config/routes.rb
Rails.application.routes.draw do
  resources :contests

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_one :sport
  has_one :site
  has_and_belongs_to_many :players
  has_and_belongs_to_many :teams
  has_and_belongs_to_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_and_belongs_to_many :teams
  has_and_belongs_to_many :contests
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  has_and_belongs_to_many :contests
end

app/models/site.rb
class Site < ActiveRecord::Base

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :teams
  has_many :players
  has_and_belongs_to_many :games
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_and_belongs_to_many :games
  has_and_belongs_to_many :contests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController

  def index
    @contest = Contest.all.order("created_at DESC")
  end

  def show

  end

  def new
    @contest=contest.build
  end

  def create
    @contest=contest.build(contests_params)

    if @contest.save
      redirect_to @contest
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @contest.update(contest_params)
      redirect_to @contest
    else
      render 'edit'
    end
  end

  def destroy
    @contest.destroy
    redirect_to contests_path
  end

  private

  def find_contest
    @contest=Contest.find(params[:id])
  end

  def contest_params
    params.require(:contest).permit()
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for @contest, html: {multipart: true} do |f| %>
    <% if @contest.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

          <ul>
            <% @contest.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, size: 80 %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body, cols: 80, rows: 40 %>
    </div>
    <div class="field">
      <%= f.label :excerpt %><br>
      <%= f.text_area :excerpt, cols: 40, rows: 5, maxlength: 160 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/contests/index.html.erb
<% @title= 'Contests' %>


<h1>Contests</h1>
<% @contests.each do |post| %>

    <%= link_to(contest.title, contest_path(contest)) %><br>
    Date: <%= contest.created_at.strftime("%m/%d/%y") %><br>
    By: <%= contest.user.username %><br>
    <%= contest.excerpt %><br>
    <%= link_to('Read More', contest_path(contest)) %>
    <br>
    <br>

<% end %>
<div class="pagination">
  <%= will_paginate @contests, previous_label: "Newer", next_label: "Older", inner_window: 2, outer_window: 0 %>
</div>

app/views/contests/show.html.erb
yes

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Df</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>